# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Workspace\Python\Content warning\CW.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import random
import string
import webbrowser
import pymem
import pymem.process
import time
import threading





class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(371, 250)
        MainWindow.setMinimumSize(QtCore.QSize(371, 250))
        MainWindow.setMaximumSize(QtCore.QSize(371, 250))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 50, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 50, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 140, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(50, 110, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(200, 140, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Content Warning Trainer"))
        self.pushButton.setText(_translate("MainWindow", "Infinite Stanima"))
        self.pushButton_2.setText(_translate("MainWindow", "Infinite Oxygen"))
        self.pushButton_3.setText(_translate("MainWindow", "Change money"))
        self.pushButton_4.setText(_translate("MainWindow", "Github"))



Moneyofsl = [0x72DF20,0x0,0x220,0x6E0,0x100,0x2C]
Up_staminaofsl = [0x7270F0,0x28, 0x100, 0x330,0x28,0x164]
Under_staminaofsl = [0x727130,0x28, 0x118, 0x28,0x164]
Oxygenofsl = [0x7D2680,0x28,0x118,0x28,0x124]


#Process Initialize
GameProcess = pymem.Pymem("Content Warning.exe")
Baseaddr = pymem.process.module_from_name(GameProcess.process_handle,'mono-2.0-bdwgc.dll').lpBaseOfDll

def money():
    MoneyLastOffsets = Moneyofsl.pop()
    moneyoffsets = Baseaddr
    try:
        for i in Moneyofsl:
            moneyoffsets += i
            moneyoffsets = GameProcess.read_longlong(moneyoffsets)
        money = GameProcess.read_int(moneyoffsets+MoneyLastOffsets)
        GameProcess.write_int(moneyoffsets+MoneyLastOffsets,int(ui.lineEdit.text()))
    except:
        ui.lineEdit.setText("change at home")

#Upstamina

def stamina():
    UpStaminaLastOffsets = Up_staminaofsl.pop()
    upoffsets = Baseaddr
    try:
        for i in Up_staminaofsl:
            upoffsets += i
            upoffsets = GameProcess.read_longlong(upoffsets)
        Upstamina = GameProcess.read_float(upoffsets+UpStaminaLastOffsets)
        #print(Upstamina)
        en1 = 1
    except:
        en1 = 0

    UnderStaminaLastOffsets = Under_staminaofsl.pop()
    underoffsets = Baseaddr
    try:
        for i in Under_staminaofsl:
            underoffsets += i
            underoffsets = GameProcess.read_longlong(underoffsets)
        Understamina = GameProcess.read_float(underoffsets+UnderStaminaLastOffsets)
        # print(Understamina)
        en2 = 1
    except:
        en2 = 0
    
    while en1:
        def clicked():
            while 1:
                GameProcess.write_float(upoffsets+UpStaminaLastOffsets,float(10.0))
        t = threading.Thread(target=clicked,daemon=True)
        t.start()
        en1 = 0
    while en2:
        def clicked2():
            while 1:
                GameProcess.write_float(underoffsets+UnderStaminaLastOffsets,float(10.0))
        t2 = threading.Thread(target=clicked2,daemon=True)
        t2.start()
        en2 = 0

#Oxygen
def oxygen():
    
    OxygenLastOffsets = Oxygenofsl.pop()
    oxygenoffsets = Baseaddr
    try:
        for i in Oxygenofsl:
            oxygenoffsets += i
            oxygenoffsets = GameProcess.read_longlong(oxygenoffsets)
            Oxygen = GameProcess.read_float(oxygenoffsets+OxygenLastOffsets)
            en = 1
        #print(Oxygen)
    except:
        en = 0
    while en:
        def clicked3():
            while 1:
                GameProcess.write_float(oxygenoffsets + OxygenLastOffsets,float(500.0))
        t3 = threading.Thread(target=clicked3,daemon=True)
        t3.start()
        en = 0

def Githubf():
    url = "https://github.com/7urtle"  
    webbrowser.open(url)

app = QtWidgets.QApplication(sys.argv)
window = QtWidgets.QMainWindow()
ui = Ui_MainWindow()
ui.setupUi(window)
window.setWindowTitle("Content Warning")
window.show()

ui.pushButton.clicked.connect(stamina)
ui.pushButton_2.clicked.connect(oxygen)
ui.pushButton_3.clicked.connect(money)
ui.pushButton_4.clicked.connect(Githubf)


sys.exit(app.exec_())


